settingGroups:
  Default:
    DEVELOPMENT_TEAM: 2NC533SE3E
    # SWIFT_VERSION: 5.1
    IPHONEOS_DEPLOYMENT_TARGET: 13.0
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
    # CLANG_ANALYZER_LOCALIZIBILITY_NONLOCALIZED: YES
    DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: YES

targetTemplates:
  Application:
    # transitivelyLinkDependencies: NO 
    deploymentTarget:
      iOS: 13.0
    settings:
      groups: [Default]
      #   DEVELOPMENT_TEAM: 2NC533SE3E
        # SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        # CLANG_ENABLE_MODULES: YES
        # CLANG_WARN_DOCUMENTATION_COMMENTS: NO
        # GCC_TREAT_WARNINGS_AS_ERRORS: YES
        # DEFINES_MODULE: YES
        # ENABLE_BITCODE: false
        # OTHER_LDFLAGS: $(inherited)
        # GCC_NO_COMMON_BLOCKS: NO
        # FRAMEWORK_SEARCH_PATHS: $(inherited)

  Module: 
    type: framework.static
    # transitivelyLinkDependencies: NO
    deploymentTarget:
      iOS: 13.0
    settings:
      groups: [Default]
      #   DEVELOPMENT_TEAM: 2NC533SE3E
        # ENABLE_BITCODE: false
        # GCC_NO_COMMON_BLOCKS: NO
        # MACH_O_TYPE: staticlib
        # OTHER_LDFLAGS: $(inherited) 
        # FRAMEWORK_SEARCH_PATHS: $(inherited)

  Pod: 
    platform: iOS
    type: framework
    settings:
      groups: [Default]
      # base: 
      #   DEVELOPMENT_TEAM: 2NC533SE3E
        # ENABLE_BITCODE: false
        # GCC_NO_COMMON_BLOCKS: NO
        # MACH_O_TYPE: mh_dylib
        # OTHER_LDFLAGS: $(inherited) 
        # FRAMEWORK_SEARCH_PATHS: $(inherited)