# This is a basic workflow to help you get started with Actions

name: "Dev Deploy"

on:
  push:
    branches:  
      - test/dev/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-core-ios:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_PAT }}
    - name: Configure HomeBrew Cache
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/bin/xcodegen
          /usr/local/bin/rome
        key: ${{ runner.os }}-ios-homebrew-${{ hashFiles('**/Brewfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-ios-homebrew-
    - name: Configure Ruby Cache
      uses: actions/cache@v2
      with:
        path: |
          vendor/
        key: ${{ runner.os }}-ios-ruby-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-ios-ruby-
    - name: Configure CocoaPods Cache
      uses: actions/cache@v2
      with:
        path: |
          Pods/
        key: ${{ runner.os }}-ios-cocoapods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-ios-cocoapods-
    - name: Configure CI Environment
      env:
        # AWS
        AWS_CONFIG: ${{ secrets.AWS_CONFIG }}
        AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
        # Firebase
        FIREBASE_SA_KEY: ${{ secrets.FIREBASE_SA_KEY }}
        FIREBASE_SA_KEY_FILE: ${{ secrets.FIREBASE_SA_KEY_FILE }}
        # Fastlane
        FASTLANE_ENV_FILE: .env.fastlane.dev
        FASTLANE_DEV_ENV: ${{ secrets.FASTLANE_DEV_ENV }}
        # Git
        GIT_API_KEY: ${{ secrets.GIT_API_KEY }}
        # Apple
        APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
      run: |
        sh bin/ci_configure_env.sh
    - name: Fastlane Build App
      run: 
        bundle exec fastlane test_and_build --env fastlane.dev --verbose
